name: tomles-update

on: 
  - push

jobs:
  pre-release:

    runs-on: ubuntu-latest
    name: tomles update

    steps:
    - uses: actions/checkout@v2

    - uses: n3wscott/tomles-action@learning7
      with:
        package: knative.dev/pkg
        branch: release-0.14

    - uses: n3wscott/dep-action@learning1

    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update Gopkg.toml via tomles'
        title: 'Update Gopkg.toml via tomles'